// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mczqwqsvumfsneoknlep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jenF3cXN2dW1mc25lb2tubGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTMwNzUsImV4cCI6MjA3NDk2OTA3NX0.iJ-snIA6M1xmdUwxOlx7E2SdxkS3JuUapE7BoCAC4K8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});